// SPDX-License-Identifier: FSL-1.1-ALv2

package inventory

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"github.com/goccy/go-yaml"
)

// File is the schema of inventory.yaml. It carries both the static device
// list and optional hostname patterns so one file can seed the whole chain.
type File struct {
	Devices []Target  `yaml:"devices,omitempty"`
	Roles   []Pattern `yaml:"roles,omitempty"`
}

// StaticFile resolves names from an in-memory device list.
type StaticFile struct {
	byName map[string]Target
}

// NewStatic builds a StaticFile from targets. Duplicate names (case-
// insensitive) are an error because two conflicting roles for one device
// would make the policy outcome depend on file order.
func NewStatic(targets []Target) (*StaticFile, error) {
	s := &StaticFile{byName: make(map[string]Target, len(targets))}
	for _, t := range targets {
		key := normalize(t.Name)
		if key == "" {
			return nil, fmt.Errorf("inventory: device without name")
		}
		if _, dup := s.byName[key]; dup {
			return nil, fmt.Errorf("inventory: duplicate device %q", t.Name)
		}
		s.byName[key] = t
	}
	return s, nil
}

// Resolve implements Resolver.
func (s *StaticFile) Resolve(name string) (Target, bool) {
	if s == nil {
		return Target{}, false
	}
	t, ok := s.byName[normalize(name)]
	return t, ok
}

// Len returns the number of devices.
func (s *StaticFile) Len() int { return len(s.byName) }

// Targets returns every device sorted by name.
func (s *StaticFile) Targets() []Target {
	out := make([]Target, 0, len(s.byName))
	for _, t := range s.byName {
		out = append(out, t)
	}
	sort.Slice(out, func(i, j int) bool { return normalize(out[i].Name) < normalize(out[j].Name) })
	return out
}

// ParseFile decodes inventory.yaml.
func ParseFile(b []byte) (*File, error) {
	var f File
	if err := yaml.UnmarshalWithOptions(b, &f, yaml.Strict()); err != nil {
		return nil, fmt.Errorf("inventory: parse: %w", err)
	}
	return &f, nil
}

// LoadFile reads and decodes inventory.yaml.
func LoadFile(path string) (*File, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("inventory: read: %w", err)
	}
	f, err := ParseFile(b)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return f, nil
}

// LoadChain reads inventory.yaml and returns a Chain of its static devices
// followed by its hostname patterns, in the order the plan prescribes.
func LoadChain(path string) (Chain, error) {
	f, err := LoadFile(path)
	if err != nil {
		return nil, err
	}
	return f.Chain()
}

// Chain builds the resolver chain for a decoded file.
func (f *File) Chain() (Chain, error) {
	static, err := NewStatic(f.Devices)
	if err != nil {
		return nil, err
	}
	patterns, err := NewPatterns(f.Roles)
	if err != nil {
		return nil, err
	}
	return Chain{static, patterns}, nil
}

// WriteFile encodes targets as inventory.yaml to w.
func WriteFile(w io.Writer, f *File) error {
	b, err := yaml.MarshalWithOptions(f, yaml.IndentSequence(true))
	if err != nil {
		return fmt.Errorf("inventory: encode: %w", err)
	}
	header := "# Fathomgate static inventory. Generated by `fathomgate inventory import`; edit freely.\n"
	if _, err := io.WriteString(w, header); err != nil {
		return err
	}
	_, err = w.Write(b)
	return err
}

// SplitTags parses a tag list given as "a,b c" or "a;b".
func SplitTags(s string) []string {
	f := strings.FieldsFunc(s, func(r rune) bool { return r == ',' || r == ';' || r == ' ' || r == '|' })
	out := make([]string, 0, len(f))
	for _, t := range f {
		if t = strings.TrimSpace(t); t != "" {
			out = append(out, t)
		}
	}
	return out
}
